"""add async track fields

Revision ID: 1804b8892c3b
Revises: fc4f76f81bb5
Create Date: 2025-11-20 14:47:58.800216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1804b8892c3b'
down_revision: Union[str, Sequence[str], None] = 'fc4f76f81bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('status', sa.String(), nullable=False))
    op.add_column('tracks', sa.Column('task_external_id', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('prompt', sa.Text(), nullable=True))
    op.alter_column('tracks', 'track_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'track_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tracks', 'prompt')
    op.drop_column('tracks', 'error')
    op.drop_column('tracks', 'task_external_id')
    op.drop_column('tracks', 'status')
    # ### end Alembic commands ###
