"""init

Revision ID: 572cb9fa04c6
Revises: 
Create Date: 2025-11-13 17:36:38.727729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '572cb9fa04c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kakao_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('social_provider', sa.String(), nullable=True),
    sa.Column('social_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=True)
    op.create_index(op.f('ix_users_social_id'), 'users', ['social_id'], unique=True)
    op.create_index(op.f('ix_users_social_provider'), 'users', ['social_provider'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('therapist_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('PENDING','ACCEPTED','REJECTED','TERMINATED')", name='ck_connections_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connections_patient', 'connections', ['patient_id'], unique=False)
    op.create_index('idx_connections_therapist', 'connections', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('initiator_type', sa.String(), nullable=True),
    sa.Column('guideline_version', sa.String(), nullable=True),
    sa.Column('input_source', sa.String(), nullable=True),
    sa.Column('prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('track_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("initiator_type in ('patient','therapist') or initiator_type is null", name='ck_sessions_initiator'),
    sa.CheckConstraint("input_source in ('patient_analyzed','therapist_manual','fallback') or input_source is null", name='ck_sessions_input_source'),
    sa.CheckConstraint("status in ('QUEUED','PROCESSING','READY','FAILED')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_created_by', 'sessions', ['created_by'], unique=False)
    op.create_index('idx_sessions_status', 'sessions', ['status'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_msg_session_time', 'conversation_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('session_patient_intake',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('vas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_dialog', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('session_prompts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('therapist_manual_inputs',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('bpm_min', sa.Integer(), nullable=True),
    sa.Column('bpm_max', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(), nullable=True),
    sa.Column('vocals_allowed', sa.Boolean(), nullable=True),
    sa.Column('include_instruments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('exclude_instruments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('track_url', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracks_session_time', 'tracks', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracks_session_time', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('therapist_manual_inputs')
    op.drop_table('session_prompts')
    op.drop_table('session_patient_intake')
    op.drop_index('idx_conv_msg_session_time', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_sessions_status', table_name='sessions')
    op.drop_index('idx_sessions_created_by', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('idx_connections_therapist', table_name='connections')
    op.drop_index('idx_connections_patient', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_social_provider'), table_name='users')
    op.drop_index(op.f('ix_users_social_id'), table_name='users')
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
