"""Add board features

Revision ID: 6a1efaeaa18a
Revises: 0d67352f0911
Create Date: 2025-11-24 15:04:21.641592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1efaeaa18a'
down_revision: Union[str, Sequence[str], None] = '0d67352f0911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_likes',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('post_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'post_id')
    )

    # --- views 컬럼 추가 (1단계: nullable=True)
    op.add_column('board_posts', sa.Column('views', sa.Integer(), nullable=True))

    # --- 기존 데이터 null → 0으로 채우기 (2단계)
    op.execute('UPDATE board_posts SET views = 0 WHERE views IS NULL')

    # --- 이제 nullable=False로 변경 (3단계)
    op.alter_column('board_posts', 'views', nullable=False)

    # tags 컬럼은 원래 nullable=True라 문제 없음
    op.add_column('board_posts', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_posts', 'tags')
    op.drop_column('board_posts', 'views')
    op.drop_table('board_likes')
    # ### end Alembic commands ###
