"""Add board features

Revision ID: 6fc0f77f8ad2
Revises: f0845d31e1c0
Create Date: 2025-11-26 14:50:47.369486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc0f77f8ad2'
down_revision: Union[str, Sequence[str], None] = 'f0845d31e1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('initiator_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'connections', 'users', ['initiator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_column('connections', 'initiator_id')
    # ### end Alembic commands ###
