"""add new table

Revision ID: 725cad728305
Revises: 7d5c0d65db46
Create Date: 2025-10-17 14:02:46.148418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725cad728305'
down_revision: Union[str, Sequence[str], None] = '7d5c0d65db46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_patient_intake',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('vas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_dialog', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('therapist_manual_inputs',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('bpm_min', sa.Integer(), nullable=True),
    sa.Column('bpm_max', sa.Integer(), nullable=True),
    sa.Column('key_signature', sa.String(), nullable=True),
    sa.Column('vocals_allowed', sa.Boolean(), nullable=True),
    sa.Column('include_instruments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('exclude_instruments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.add_column('sessions', sa.Column('initiator_type', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('guideline_version', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('input_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'input_source')
    op.drop_column('sessions', 'guideline_version')
    op.drop_column('sessions', 'initiator_type')
    op.drop_table('therapist_manual_inputs')
    op.drop_table('session_patient_intake')
    # ### end Alembic commands ###
