"""add new table

Revision ID: 762367dbefd6
Revises: 5f0c84386f7d
Create Date: 2025-10-30 17:15:39.948144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762367dbefd6'
down_revision: Union[str, Sequence[str], None] = '5f0c84386f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('therapist_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('PENDING','ACCEPTED','REJECTED','TERMINATED')", name='ck_connections_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connections_patient', 'connections', ['patient_id'], unique=False)
    op.create_index('idx_connections_therapist', 'connections', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        sa.text("UPDATE users SET name = '기본 사용자 이름' WHERE name IS NULL")
    )

    # 3. 'name' 열을 NOT NULL로 변경합니다.
    op.alter_column('users', 'name', 
               existing_type=sa.String(),
               nullable=False,
               # server_default=None # 만약 기존에 설정된 server_default가 있다면 제거
               )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('idx_connections_therapist', table_name='connections')
    op.drop_index('idx_connections_patient', table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
