"""update table

Revision ID: 7d5c0d65db46
Revises: c4400f9fc8f8
Create Date: 2025-10-16 11:49:48.515091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5c0d65db46'
down_revision: Union[str, Sequence[str], None] = 'c4400f9fc8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_msg_session_time', 'conversation_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('session_prompts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('track_url', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracks_session_time', 'tracks', ['session_id', 'created_at'], unique=False)
    op.add_column('sessions', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('sessions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('sessions', sa.Column('prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('track_url', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('idx_sessions_created_by', 'sessions', ['created_by'], unique=False)
    op.create_index('idx_sessions_status', 'sessions', ['status'], unique=False)
    op.create_foreign_key(None, 'sessions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('sessions', 'target_metric')
    op.drop_column('sessions', 'patient_id')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.add_column('sessions', sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('target_metric', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index('idx_sessions_status', table_name='sessions')
    op.drop_index('idx_sessions_created_by', table_name='sessions')
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'provider')
    op.drop_column('sessions', 'track_url')
    op.drop_column('sessions', 'prompt')
    op.drop_column('sessions', 'status')
    op.drop_column('sessions', 'created_by')
    op.drop_index('idx_tracks_session_time', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('session_prompts')
    op.drop_index('idx_conv_msg_session_time', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
