"""add async track fields

Revision ID: 81e05e92dfa4
Revises: 
Create Date: 2025-11-20 17:37:47.821333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e05e92dfa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('track_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_posts_id'), 'board_posts', ['id'], unique=False)
    op.create_table('board_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_comments_id'), 'board_comments', ['id'], unique=False)
    op.add_column('tracks', sa.Column('status', sa.String(), nullable=False))
    op.add_column('tracks', sa.Column('task_external_id', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('prompt', sa.Text(), nullable=True))
    op.alter_column('tracks', 'track_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'track_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tracks', 'prompt')
    op.drop_column('tracks', 'error')
    op.drop_column('tracks', 'task_external_id')
    op.drop_column('tracks', 'status')
    op.drop_index(op.f('ix_board_comments_id'), table_name='board_comments')
    op.drop_table('board_comments')
    op.drop_index(op.f('ix_board_posts_id'), table_name='board_posts')
    op.drop_table('board_posts')
    # ### end Alembic commands ###
