"""Add name column to User table

Revision ID: a531501d63a1
Revises: 4c5c67ba0f8f
Create Date: 2025-10-31 10:48:20.434386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a531501d63a1'
down_revision: Union[str, Sequence[str], None] = '4c5c67ba0f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('therapist_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('PENDING','ACCEPTED','REJECTED','TERMINATED')", name='ck_connections_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connections_patient', 'connections', ['patient_id'], unique=False)
    op.create_index('idx_connections_therapist', 'connections', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index('idx_connections_therapist', table_name='connections')
    op.drop_index('idx_connections_patient', table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
