"""Add board features

Revision ID: bc725ad4d1fc
Revises: d1f1522770ab
Create Date: 2025-11-25 15:25:38.271998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc725ad4d1fc'
down_revision: Union[str, Sequence[str], None] = 'd1f1522770ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('users', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
