"""add new table

Revision ID: c4400f9fc8f8
Revises: 9f90c2e45008
Create Date: 2025-10-15 14:08:11.606877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4400f9fc8f8'
down_revision: Union[str, Sequence[str], None] = '9f90c2e45008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target_metric', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    # ### end Alembic commands ###
