"""init

Revision ID: fc4f76f81bb5
Revises: 
Create Date: 2025-11-17 16:30:59.662604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4f76f81bb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counselor_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('therapist_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_patient_therapist', 'counselor_notes', ['patient_id', 'therapist_id'], unique=False)
    op.create_index(op.f('ix_counselor_notes_id'), 'counselor_notes', ['id'], unique=False)
    op.add_column('tracks', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tracks', 'is_favorite')
    op.drop_index(op.f('ix_counselor_notes_id'), table_name='counselor_notes')
    op.drop_index('idx_notes_patient_therapist', table_name='counselor_notes')
    op.drop_table('counselor_notes')
    # ### end Alembic commands ###
